// app/layout.tsx
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google"; // <--- REMOVE THIS LINE
import { GeistSans } from '@vercel/geist/sans'; // Import GeistSans
import { GeistMono } from '@vercel/geist/mono'; // Import GeistMono

import "./globals.css";

// You no longer need to call Geist() or Geist_Mono() as they are already instances
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "CFB 26 TeamBuilder Auto-Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Directly use GeistSans.variable and GeistMono.variable
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}